name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env to release Environment
        if: contains(github.ref, 'main/')  ||  contains(github.ref, 'hotfix/')
        run: |
          echo "main"
          echo "secrets added directly from reusable ${{ secrets.SECRET2 }}"
          echo "secrets from main workflow secrets  ${{ inputs.config-path }}"
      - name: Set env to release Environment
        if: contains(github.ref, 'main/')  ||  contains(github.ref, 'hotfix/')
        run: |
          echo "not in main"
          ehco ${{ secrets.SECRET1 }}
