on:
  push:
    branches:
      - main

name: dashboard-api-github-actions-flow

jobs:
  dashboard_api_build_and_push_to_ECR:
    name: build and push to ECR dashboard_api
    runs-on: ubuntu-latest

    steps:         
      - uses: actions/checkout@v3         
      - name: echo 
        run: |
          echo "asdfadsf"
          event_name=guna
          echo "event_name=${event_name}" >> ${GITHUB_OUTPUT}
      - uses: gunahk/github-dirty-hands-on/.github/reuseabllw/action.yaml
        when: 
          config-path: test
          secrets: ${{ secrets.SECRET2 }}