# Create .github/workflows/sync-on-dispatch.yml
name: Sync on Deployment Complete

on:
  repository_dispatch:
    types: [deployment-complete]

jobs:
  create-sync-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Create sync PR
        uses: actions/github-script@v6
        with:
          script: |
            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Auto-sync: master → develop',
              head: 'master',
              base: 'develop',
              body: 'Automated sync after deployment completion'
            });
            
            // Enable auto-merge
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.data.number,
              merge_method: 'merge'
            });
