# .github/workflows/sync-master-to-develop.yml
name: Auto-sync Master to Develop

on:
  push:
    branches: [master, main]  # Trigger on pushes to master/main branch
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
    
    steps:
      - name: asdf
        run: |
          echo "asdfsadf"
