name: Single Job Workflow

on:
  push:
    branches:
      - main

jobs:
  job_selector:
    runs-on: ubuntu-latest
    outputs:
      job_number: ${{ steps.select_job.outputs.job_number }}
    steps:
      - name: Select Job
        id: select_job
        run: |
          job_number::$(echo $(((${GITHUB_RUN_NUMBER} % 5) + 1))) >> ${GITHUB_OUTPUT}

  job1:
    runs-on: ubuntu-latest
    if: ${{ needs.job_selector.outputs.job_number == '1' }}
    steps:
      - name: Step 1 for Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    if: ${{ needs.job_selector.outputs.job_number == '2' }}
    steps:
      - name: Step 1 for Job 2
        run: echo "This is job 2"

  job3:
    runs-on: ubuntu-latest
    if: ${{ needs.job_selector.outputs.job_number == '3' }}
    steps:
      - name: Step 1 for Job 3
        run: echo "This is job 3"

  job4:
    runs-on: ubuntu-latest
    if: ${{ needs.job_selector.outputs.job_number == '4' }}
    steps:
      - name: Step 1 for Job 4
        run: echo "This is job 4"

  job5:
    runs-on: ubuntu-latest
    if: ${{ needs.job_selector.outputs.job_number == '5' }}
    steps:
      - name: Step 1 for Job 4
        run: echo "This is job 4"
   
