on:
  push:
    branches:
      - main

jobs:
  verify_source_branch:
    runs-on: ubuntu-latest  # Or your preferred runner

    steps:
      - uses: actions/checkout@v3  # Checkout the repository

      - name: Get source branch name k
        run: |
          source_branch=$(git merge-base main HEAD)
          echo "Source branch for this merge: $source_branch"

          if [[ "$source_branch" == "refs/heads/develop" ]]; then
              echo "Successfully merged from develop branch!"
          else
              echo "This merge originated from branch: $source_branch"
              # Add additional steps here if you want to perform actions based on the source branch
          fi
