name: testing
on:
  push:
    branches:
      - main
run-name: Deploying to environment for branch ${{ github.ref_name }} by ${{ github.actor }}

jobs:
  master_dashboard_app_deploy_to_EKS_Cluster:
    name: asdfasdfadsfasfasdfa
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Versing of Tag based on the pull request Branch Name
        id: semantic-versing  
        continue-on-error: false 
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          endpoint: ${{ inputs.API_ENDPOINT_WITH_HTTPS }}
        run: |
          exit 1;
          
      - name: asdfasdf Versing of Tag based on the pull request Branch Name
        id: semantic-asdfasdf  
        run: |
          echo "contine"


      - name: Notify Slack Action
        uses: ravsamhq/notify-slack-action@2.3.0
        if: ${{ always() && github.ref_name == 'main' }}
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
          notification_title: '{workflow} is failing'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK_DEV }}
