name: testing
on:
  push:
    branches:
      - main
run-name: Deploying to environment for branch ${{ github.ref_name }} by ${{ github.actor }}

jobs:
  master_dashboard_app_deploy_to_EKS_Cluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Necessary to access local action
      - name: Local Action Call
        uses: ./.github/workflows/reuseabllw/action.yaml
        with: 
          image_name: v1.2
          tag: 1.2
          SECRET2: ${{ secrets.SECRET2}}
          TOKEN: ${{ secrets.TOKEN}}
    
