name: Single Job Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job1:
    runs-on: ubuntu-latest
    if: github.run_number == 1
    steps:
      - name: Step 1
        run: echo "This is my first job"

  my_job2:
    runs-on: ubuntu-latest
    if: github.run_number == 2
    steps:
      - name: Step 1
        run: echo "This is my second job"

  my_job3:
    runs-on: ubuntu-latest
    if: github.run_number == 3
    steps:
      - name: Step 1
        run: echo "This is my third job"

  my_job4:
    runs-on: ubuntu-latest
    if: github.run_number == 4
    steps:
      - name: Step 1
        run: echo "This is my fourth job"

  my_job5:
    runs-on: ubuntu-latest
    if: github.run_number == 5
    steps:
      - name: Step 1
        run: echo "This is my fifth job"
