name: testing

on:
  push:
    branches:
      - main

jobs:
  master_dashboard_app_deploy_to_EKS_Cluster:
    name: fasdf
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Versing of Tag based on the pull request Branch Name
        id: semantic-versing  
        run: |
          # Input base_merge_ref
          base_merge_ref=$(echo "$GITHUB_CONTEXT" | jq -r '.event.commits[] | select(.distinct == true) | .message' | grep -oE 'Merge pull request #[0-9]+ from [^/]+/[^"]+' | tail -n 1 | awk '{print $NF}' | cut -d "/" -f 2)
          echo $base_merge_ref
          # Check base_merge_ref and update semantic version accordingly
          if [ "$base_merge_ref" == "release" ]; then
              
              echo "$base_merge_ref hotfix"
          elif [ "$base_merge_ref" == "feature" ]; then
              echo "$base_merge_ref hotfix"
          elif [ "$base_merge_ref" == "hotfix" ]; then
              echo "$base_merge_ref hotfix"
          else
              # Increment patch version
              echo "Increment patch version"
          fi
          echo "Image tag Formate is ${latest_image_tag}"
          # Image tag format
          echo "IMAGE_TAG=${latest_image_tag}" >> $GITHUB_ENV
  
