name: testing
on:
  push:
    branches:
      - main
run-name: Deploying to environment for branch ${{ github.ref_name }} by ${{ github.actor }}

jobs:
  master_dashboard_app_deploy_to_EKS_Cluster:
    uses: ./.github/workflows/reuseabllw.yaml@main
    with: 
      image_name: v1.2
      tag: 1.2
    secrets:
      SECRET2: ${{ secrets.SECRET2}}
      TOKEN: ${{ secrets.TOKEN}}
    
