name: testing

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: select the environment
        options: 
        - develop
        - master
      image:
        description: 'Please check the dashboard app image tag and paste here'
        required: true

jobs:
  master_dashboard_app_deploy_to_EKS_Cluster:
    name: fasdf
    runs-on: ubuntu-latest
    steps:
      - name: Load values for 'develop' environment
        if: ${{ github.event.inputs.environment == 'develop' }}
        env:
          image: ${{ github.event.inputs.image }}
          environment: ${{ github.event.inputs.environment }}
          acter: ${{ github.actor }}
        run: |
          # Switch to AWS based on environments
          echo "I AM IN SAME AWS ACCOUNT AS GITHUB ACTIONS"

      - name: Load values for 'develop' environment
        if: ${{ github.event.inputs.environment == 'master' }}
        env:
          image: ${{ github.event.inputs.image }}
          environment: ${{ github.event.inputs.environment }}
          acter: ${{ github.actor }}
        run: |
          # Switch to AWS based on environments
          echo "master"
          echo $environment
          echo $image
          key=value
          echo "key1=${key}" >> $GITHUB_ENV

      - name: Summary
        env:
          image: ${{ github.event.inputs.image }}
          environment: ${{ github.event.inputs.environment }}
          acter: ${{ github.actor }}
          key: ${{ env.key1 }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY <<EOF
          ### Deleted Environment:
          **Environment:** $environment
          **image:** $image
          **acter:** $acter
          **key:** $key
