name: testing
on:
  workflow_dispatch:
    inputs:
      API_ENDPOINT_WITH_HTTPS:
        description: 
          >
            HTTPS Endpoint of api 
            for release/hotfix please use
            https://api-release.zluri.com
            https://api-hotfix.zluri.com
            https://api.zluri.com
        required: true
        default: https://api.zluri.com

run-name: Deploying to environment for branch ${{ github.ref_name }} by ${{ github.actor }}

jobs:
  master_dashboard_app_deploy_to_EKS_Cluster:
    name: asdfasdfadsfasfasdfa
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Versing of Tag based on the pull request Branch Name
        id: semantic-versing  
        continue-on-error: false 
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          endpoint: ${{ inputs.API_ENDPOINT_WITH_HTTPS }}
        run: |
          if [[ "$endpoint" == "https://api-hotfix.zluri.com" || "$endpoint" == "https://api.zluri.com" || "$endpoint" == "https://api-release.zluri.com" ]]; then
            echo "Endpoint $endpoint is valid."
          else
            echo "Endpoint $endpoint is not valid please check and Enter the correct API URL"
            echo "Exiting!!"
            exit 0
          fi
          echo "contine"

      - name: asdfasdf Versing of Tag based on the pull request Branch Name
        id: semantic-asdfasdf  
        run: |
          echo "contine"

          
