name: Single Job Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    if: ${{ github.run_number % 5 == 1 }}  # Runs if run number modulo 5 is 1
    steps:
      - name: Step 1 for Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    if: ${{ github.run_number % 5 == 2 }}  # Runs if run number modulo 5 is 2
    steps:
      - name: Step 1 for Job 2
        run: | 
          echo "IMAGE_TAG=23" >> ${GITHUB_OUTPUT}

    outputs:
      IMAGE_TAG: ${{ steps.push-image.outputs.IMAGE_TAG }}

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - name: Step 1 for Job 3
        run: | 
          echo ${GITHUB_OUTPUT}
          

  job4:
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name: Step 1 for Job 4
        run: echo $IMAGE_TAG

  job5:
    runs-on: ubuntu-latest
    needs: job4
    steps:
      - name: Step 1 for Job 5
        run: echo "This is job 5"
