name: Single Job Workflow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 for Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 for Job 2
        id: push-image
        run: | 
          echo "IMAGE_TAG=23" >> ${GITHUB_OUTPUT}

    outputs:
      IMAGE_TAG: ${{ steps.push-image.outputs.IMAGE_TAG }}

  job3:
    runs-on: ubuntu-latest
    needs: 
      - job2
    steps:
      - name: Step 1 for Job 3
        env:
          IMAGE_TAG: ${{ needs.job2.outputs.IMAGE_TAG }}
        run: | 
          echo ${IMAGE_TAG}
          

  job4:
    runs-on: ubuntu-latest
    needs: 
      - job2
      - job3
    steps:
      - name: Step 1 for Job 4
        env:
          IMAGE_TAG: ${{ needs.job2.outputs.IMAGE_TAG }}
        run: | 
          echo ${IMAGE_TAG}


  job5:
    runs-on: ubuntu-latest
    needs: 
      - job4
      - job2
    steps:
      - name: Step 1 for Job 5
        env:
          IMAGE_TAG: ${{ needs.job2.outputs.IMAGE_TAG }}
        run: | 
          echo ${IMAGE_TAG}

        
