on:
  pull_request:
    branches:
      - main
      - staging
      - master
    types:
      - closed

name: Create or deploy to environment
run-name: Deploying to environment for branch ${{ github.ref_name }} by ${{ github.actor }}
jobs:
  dashboard_api_build_and_push_to_ECR:
    name: build and push to ECR dashboard_api
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main'

      - name: echo 
        id: step
        run: |
          ls -ltra
