on:
  push:
    branches:
      - main
      - feature/*
      - release/*
      - hotfix/*
      


jobs:
  checkout-destination-branch:
    runs-on: ${{ contains(github.ref, 'feature/') && 'dev-cd-deploy' || (contains(github.ref, 'release/') || contains(github.ref, 'hotfix/')) && 'prod-cd-deploy' || 'default-runner' }}
    defaults:
      run:
        working-directory: ./postgress
    steps:
      # Step 1: Checkout the repository metadata
      - name: Checkout Repository Metadata
        uses: actions/checkout@v4

      - name: Run Commands in Postgress Directory        
        run: |
          echo "Current directory: $(pwd)"
          ls -la

      - name: Run Commands in Postgress Directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la
