name: My GitHub Action

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Choose an option: option1, option2, option3'
        required: true
        default: 'default_value'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check parameter value
        run: echo "The value of param1 is ${{ parameters.param1 }}"
