name: Manual Workflow Trigger

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to check out'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch_name }}
