on:
  pull_request:
    branches:
      - main
      - develop
    types:
      - closed
  # Trigger manully
  workflow_dispatch:
    inputs:
      version:
        description: 'type any version'
        required: true


jobs:
  get_deployment_details:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./postgress
    steps:
      # Step 1: Checkout the repository metadata
      - name: Checkout Repository Metadata
        uses: actions/checkout@v4

    outputs:
      merged: ${{ github.event.pull_request.merged || github.event_name == 'workflow_dispatch' }}
      base_ref: ${{ github.event.pull_request.base.ref || github.ref }}
      head: ${{ github.event.pull_request.head.ref || github.event.inputs.version }}


  echo_outputs:
    runs-on: ubuntu-latest
    needs: get_deployment_details # Ensure this job runs after get_deployment_details
    steps:
      - name: Echo Outputs
        run: |
          echo "Merged: ${{ needs.get_deployment_details.outputs.merged }}"
          echo "Base Ref: ${{ needs.get_deployment_details.outputs.base_ref }}"
          echo "Head: ${{ needs.get_deployment_details.outputs.head }}"
