name: Full Workflow with PR and Notifications

on:
  push:
    branches:
      - master  # Trigger this workflow when pushing to the master branch

jobs:
  full-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Create Intermediate Branch from master
        run: |
          git checkout master
          git pull origin master
          git checkout -b intermediate-branch
          git push origin intermediate-branch

      - name: Create Pull Request from intermediate to develop
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          head: intermediate-branch
          title: "Automated PR from intermediate-branch"
          body: "This is an automated pull request from intermediate-branch to develop."
          draft: false

      - name: Check if PR has conflicts
        id: check_pr
        run: |
          pr_url="https://api.github.com/repos/${{ github.repository }}/pulls"
          pr_number=$(curl -s $pr_url | jq '.[0].number')
          pr_status=$(curl -s $pr_url/$pr_number | jq '.mergeable')
          echo "mergeable=$pr_status" >> $GITHUB_ENV

      - name: Slack Notification if PR has conflicts
        if: ${{ env.mergeable == 'false' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The pull request from intermediate-branch to develop has conflicts."}' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Merge PR if no conflicts
        if: ${{ env.mergeable == 'true' }}
        run: |
          pr_number=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls | jq '.[0].number')
          curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"commit_title": "Merge intermediate-branch to develop", "merge_method": "merge"}' \
          "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge"

      - name: Slack Notification of successful merge
        if: ${{ env.mergeable == 'true' }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"The pull request from intermediate-branch to develop was successfully merged."}' ${{ secrets.SLACK_WEBHOOK_URL }}
