on:
  push:
    branches:
      - main


jobs:
  checkout-destination-branch:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the destination branch (target branch of the PR)
      - name: Checkout destination branch
        uses: actions/checkout@v4

      - name: Confirm checked-out branch
        run: |
          cd postgress  
          ls -ltra    

      - name: Confirm down strem jobs folders
        run: |
          ls -ltra      