on:
  push:
    branches:
      - main

name: dashboard-api-github-actions-flow

jobs:
  dashboard_api_build_and_push_to_ECR:
    name: build and push to ECR dashboard_api
    runs-on: ubuntu-latest
    steps:                  
      - name: echo 
        run: |
          echo "asdfadsf"
          event_name=guna
          echo "event_name=${event_name}" >> ${GITHUB_OUTPUT}
  dashboard_api_build_and_push_to_2:
    needs: dashboard_api_build_and_push_to_ECR
    name: build and push to ECR dashboard_api asd
    runs-on: ubuntu-latest
    steps:                  
      - name: echo 
        id: step
        run: |
          echo "asdfasdf"
          echo "hotfix=true" >> $GITHUB_ENV
          echo ${{ env.hotfix }}
    outputs:
      deploy-status: ${{ steps.step.outputs.hotfix }}

  dashboard_api_build_and_push_to_ECR_2:
    name: build and push  asdf to ECR dashboard_api
    if: needs.dashboard_api_build_and_push_to_2.outputs.deploy-status == 'true'
    runs-on: ubuntu-latest
    needs: 
      - dashboard_api_build_and_push_to_2
    steps:                  
      - name: echo 
        run: |
          echo "asdfadsf"
