name: Test deployment
on:
  pull_request:
    types:
    - closed
    branches:
    - main

jobs:
  dashboard_api_build_and_push_to_ECR:
    name: build and push to ECR dashboard_api
    runs-on: ubuntu-latest
    steps:                  
      - name: echo 
        id: step
        run: |
          echo "asdlkfadsf"
          event_name=guna
          echo "asdfasdf"
          echo "hotfix=true" >> ${GITHUB_OUTPUT}
          echo "event_name=${event_name}" >> ${GITHUB_OUTPUT}
          
          BASE_BRANCH="${{ github.event.pull_request.base.ref }}"
          if [[ "$BASE_BRANCH" =~ ^feature/ || "$BASE_BRANCH" =~ ^hotfix/ ]]; then
            echo "Pull request is from a feature or hotfix branch."
          else
            echo "Pull request is not from a feature or hotfix branch"
          fi

    outputs:
      deploy-status: ${{ steps.step.outputs.hotfix }}


  dashboard_api_build_and_push_to_2:
    needs: dashboard_api_build_and_push_to_ECR
    name: build and push to ECR dashboard_api asd
    runs-on: ubuntu-latest
    steps:                  
      - name: echo 
        id: step
        if: contains(github.event.pull_request.base.ref, 'develop') 
        run: |
          echo "asdfasdf"
          #echo "hotfix=false" >> ${GITHUB_OUTPUT}
    outputs:
      deploy-status: ${{ steps.step.outputs.hotfix }}

  dashboard_api_build_and_push_to_ECR_2:
    name: build and push  asdf to ECR dashboard_api
    if: needs.dashboard_api_build_and_push_to_ECR.outputs.deploy-status == 'true'
    runs-on: ubuntu-latest
    needs: 
      - dashboard_api_build_and_push_to_2
    steps:                  
      - name: echo 
        if: contains(github.event.pull_request.head.ref, 'ggg')
        run: |
          echo "asdfadsf"

  dashboard_api_build_and_push_to_ECR_23:
    name: build and push  asdfasdf to ECR dashboard_api
    if: needs.dashboard_api_build_and_push_to_2.outputs.deploy-status == 'false'
    runs-on: ubuntu-latest
    needs: 
      - dashboard_api_build_and_push_to_2
    steps:                  
      - name: echo 
        run: |
          echo "asdfadsf"
