on:
  pull_request:
    branches:
      - main
      - master  # Example for multiple destination branches if needed
    types:
      - closed


jobs:
  checkout-destination-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    concurrency:
      group: ${{ github.ref }}  # Ensures that only one workflow per branch is active
      cancel-in-progress: true  # Cancels any currently running workflow when a new one is triggered

    
    steps:
      # Checkout the destination branch (target branch of the PR)
      - name: Checkout destination branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}


      - name: Confirm checked-out branch
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.base_ref }}
          echo "Checked out $(git branch --show-current)"
          ACTIONS_ACTOR=${{ github.actor }}
          GPT_ACTOR=${{ github.event.sender.login }}"
          

      - name: echo 
        id: step
        run: |
          ls -ltra
