on:
  pull_request:
    branches:
      - main
      - master  # Example for multiple destination branches if needed

jobs:
  checkout-destination-branch:
    runs-on: ubuntu-latest
    steps:
      # Checkout the destination branch (target branch of the PR)
      - name: Checkout destination branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Confirm checked-out branch
        run: |
          echo ${{ github.base_ref }}
          echo "Checked out $(git branch --show-current)"
          

      - name: echo 
        id: step
        run: |
          ls -ltra
