name: My GitHub Action

on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Choose an option: option1, option2, option3'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check parameter value
        run: |
          case ${{ github.event.inputs.param1 }} in
            option1)
              echo "Option 1 selected."
              # Your workflow steps for option 1
              ;;
            option2)
              echo "Option 2 selected."
              # Your workflow steps for option 2
              ;;
            option3)
              echo "Option 3 selected."
              # Your workflow steps for option 3
              ;;
            *)
              echo "Invalid option selected."
              exit 1
              ;;
          esac
          echo "executed success fully"
          echo "${{ github.event.inputs }}"
