on:
  push:
    branches:
      - main


jobs:
  checkout-destination-branch:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the destination branch (target branch of the PR)
      - name: Checkout destination branch
        uses: actions/checkout@v4
        with:
          path: postgress

      - name: Confirm checked-out branch
        run: |
          ls -ltra postgress/      