
name: Create and Publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      SECRET2:
        required: true
      TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
            
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
          echo "HELM_GIT_REPO=${{ secrets.SECRET1}}" >> $GITHUB_ENV

      - name: echo inbuild secrets 
        run: |
           echo ${{ env.HELM_GIT_REPO }}

      - name: echo call secrets 
        run: |
           echo  ${{secrets.SECRET2}}
           echo  ${{secrets.TOKEN}}
           

