name: Your Workflow Name

on:
  push:
    branches:
      - dev
      - main

jobs:
  job-dev-1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps for job on dev branch

  job-dev-2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps for another job on dev branch

  job-prod-1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps for job on prod branch, common with dev

  job-prod-2:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add steps for another job on prod branch, additional to dev
