name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ${{ startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/hotfix') && 'self-hosted-runner' || 'cd-deploy' }}
    steps:
      - name: Set env to deploy-develop Environment
        run: |
          echo "exute"


