name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ${{ startsWith(github.ref, 'refs/heads/release') || startsWith(github.ref, 'refs/heads/hotfix') && 'self-hosted-runner' || 'cd-deploy' }}
    steps:
      - name: Echo Inputs
        env:
          REF: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
        run: |
          # Export this out so others can use it
          echo "REF=${REF}" >> $GITHUB_ENV



