name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ${{ contains(github.ref, 'feature/') && 'prod-cd-deploy' || 'zluri-self-hosted-iam-role' }}
    steps:
      - name: Set env to deploy-develop Environment
        run: |
          echo "exute"


