name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ${{ github.ref_name == 'feature/*'  && 'runner' || 'cd-deploy' }}
    steps:
      - name: Set env to deploy-develop Environment
        run: |
          echo "exuteasdf"

