name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ${{ github.ref_name == 'feature/*' && 'prod-cd-deploy' || 'zluri-self-hosted-iam-role' }}

    steps:
      - name: Set env to deploy-develop Environment
        if: contains(github.ref, 'feature/')
        run: |
          echo "exute"


