name: CI

on:
  push:
    branches:
      - main
      - release/*
      - feature/*
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: load env from github env
      env: 
        AWS_ACCOUNT_ID: ${GITHUB_SHA::7}
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
        echo $AWS_ACCOUNT_ID
        echo ${{ github.ref_name }}
        echo ${{ github.ref  }}

    - name: Check Branch Name
      id: check_branch_name
      run: echo "::set-output name=branch_name::${{ github.ref_name }}"

    - name: Run Workflow If Branch Does Not Match 
      if:  ${{ steps.check_branch_name.outputs.branch_name != 'feature' }} ||  ${{ steps.check_branch_name.outputs.branch_name != 'release' }}
      run: |
        # Your workflow steps here
        echo "This workflow runs when the branch name does not match 'your-pattern'."
