on:
  pull_request:
    types: closed
    branches: 
    - '!manster'
    - '!develop'
    - '/feature/*'
    - '/hotfix/*'
    - '/release/*'
    

name: Delete Environment
run-name: Delete environment for branch ${{ github.event.pull_request && github.head_ref || github.ref_name }} by ${{ github.actor }}

jobs:
  environment_delete:
    name: Delete Environment
    runs-on: ubuntu

    steps:
      - name: Echo Inputs
        env:
          REF: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
        run: |
          # Export this out now so that others can use it
          echo "testing"
          echo $REF
