name: CI

on:
  push:
    branches:
      - main
      - release/*
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: load env from github env
      env: 
        AWS_ACCOUNT_ID: ${GITHUB_SHA::7}
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
        echo $AWS_ACCOUNT_ID
        echo ${{ github.ref_name }}

    - name: Check if branch matches pattern
      if: contains(github.ref, 'release/')
      run: |
          if [[  "${{ github.ref }}" =~ 'release/' ]]; then
            release_name=$(echo ${{ github.ref_name }}  | cut -d'/' -f4)
            echo $release_name
            # Change helm name, namespace, Autoscalling and Endpoint
            HELM_NAME=${release_name}-helm
            HELM_NAMESPACE=${release_name}-ns
          fi
            echo "$HELM_NAME $HELM_NAMESPACE"
        
