name: CI

on:
  push:
    branches:
      - main 
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Building Docker Image
      run: |
        echo DOCKER_TAG=${DOCKER_TAG}
        echo "docker build -t weblinktechs2021/${MICROSERVICE_NAME}:${DOCKER_TAG} --build-arg JAR_FILE=cdc-detector-*-SNAPSHOT.jar ."
        echo "docker push weblinktechs2021/${MICROSERVICE_NAME}:${DOCKER_TAG}"        
      env:
        DOCKER_TAG: ${GITHUB_REF##*/}-${GITHUB_SHA::7}-$(TZ=':Asia/Kolkata' date +%Y-%m-%d-%H-%M-%S)
        MICROSERVICE_NAME: cdc-detector
