name: CI

on:
  push:
    branches:
      - main
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: load env from github env
      env: 
        AWS_ACCOUNT_ID: ${GITHUB_REF##*/}-${GITHUB_SHA::7}-$(TZ=':Asia/Kolkata' date +%Y-%m-%d-%H-%M-%S)"
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
        echo $AWS_ACCOUNT_ID
