workflow_dispatch:
     inputs:
      teamName:
        type: choice
        description: "Supported Teams"
        required: true
        default: 'HackRockAthon'
        options:
              - 1
              - 2
              - 3
      xmlTestSuite:
         type: filterChoice
         description: 'XML Test Suite'
         required: true
         default: ''
         dependsOn: teamName
         options:
           optionsFor: 1
               - SQLInjection.xml
               - BlackBox.xml
            optionsFor: 2
               - smoke.xml
               - regression.xml
               - sanity.xml
            optionsFor: 3
               - InvoiceChecks.xml
               - PricingChecks.xml
    
name: Delete Environment
run-name: Delete environment for branch ${{ github.event.pull_request && github.head_ref || github.ref_name }} by ${{ github.actor }}

jobs:
  environment_delete:
    name: Delete Environment
    runs-on: ubuntu

    steps:
      - name: Echo Inputs
        env:
          REF: ${{ github.event.pull_request && github.head_ref || github.ref_name }}
        run: |
          # Export this out now so that others can use it
          echo "testing"
          echo $REF
