name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'feature/*' && 'prod-cd-deploy' || 'zluri-self-hosted-iam-role' }}


