name: CI

on:
  pull_request: {}
  push:
    branches:
      - gunahk-patch-1 
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Check if branch matches pattern
      if: contains(github.ref, 'release/') || endsWith(github.ref, '/main')
      run: |
          echo "Branch matches the pattern." 
          echo "Branch does not match the pattern."

