name: CI

on:
  push:
    branches:
      - main
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: load env from github env
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
