name: CI

on:
  push:
    branches:
      - main 
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Building Docker Image
      run: |
        echo "${{GITHUB_PATH}}"
        echo "${{GITHUB_STEP_SUMMARY}}"
        echo "${{GITHUB_PATH}}"
        echo "${{GITHUB_PATH}}"
