name: CI

on:
  push:
    branches:
      - main
      - release-*
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: load env from github env
      env: 
        AWS_ACCOUNT_ID: ${GITHUB_SHA::7}
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
        echo $AWS_ACCOUNT_ID
        echo ${{ github.ref_name }}

    - name: Check if branch matches pattern
      run: |
        if [[ ${{ github.ref }} =~ ^refs/heads/release-.* ]]; then
          echo "Branch matches the pattern."
        else
          echo "Branch does not match the pattern."
        fi
