name: Your Workflow Name

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  job-prod-2:
    runs-on: ${{ (startsWith(github.ref, 'refs/heads/feature') || startsWith(github.ref, 'refs/heads/hotfix')) && 'runner' || 'cd-deploy' }}

    steps:
      - name: Set env to deploy-develop Environment
        run: |
          echo "exuteasdf"

