name: CI

on:
  push:
    branches:
      - main
      - release/test
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: load env from github env
      env: 
        AWS_ACCOUNT_ID: ${GITHUB_SHA::7}
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
        echo $AWS_ACCOUNT_ID
        echo ${{ github.ref_name }}


    - name: test env from github env
      if: github.ref == refs/heads/release/test
      run: |
        echo ${{ github.event.repository.name }}-${GITHUB_REF##*/}:latest
        echo $AWS_ACCOUNT_ID
        echo ${{ github.ref_name }}

