name: CI

on:
  push:
    branches:
      - main 
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Check PR labels action step
      id: check_pr_labels
      uses: shioyang/check-pr-labels-on-push-action@v1.0.3
      with:
        github-token: ${{ secrets.TOKEN }}
        labels: '["bug"]'
        
    - name: See result
      run: echo "${{ steps.check_pr_labels.outputs.result }}"

    - name: true step
      if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
      run: echo "testing the ok function"

    - name: false step
      if: ${{ steps.check_pr_labels.outputs.result != 'true' }}
      run: echo "testing the ok function"
