name: CI

on:
  push:
    branches:
      - main
  
jobs:
  check_pr_labels_job:
    runs-on: ubuntu-latest
    name: A job to check the PR labels contain given labels
    steps:
    - name: Authenticate to the Code Articatory
      id: login-codeartifact
      run: |
        export CODEARTIFACT_AUTH_TOKEN=aws
        PIP_GLOBAL_INDEX_URL=https://aws:$CODEARTIFACT_AUTH_TOKEN@d.codeartifactamazonaws.com/pypi/pypi-store/simple/
        echo $PIP_GLOBAL_INDEX_URL
        echo "PIP_GLOBAL_INDEX_URL=${PIP_GLOBAL_INDEX_URL}" >> $GITHUB_ENV

    - name: echo
      run: |
        echo ${PIP_GLOBAL_INDEX_URL}
        echo ${{ env.PIP_GLOBAL_INDEX_URL }}
        
